//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroForge_OnceAgain.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeroForge_OnceAgain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure to clear stats, descriptins and selections in this form?.
        /// </summary>
        public static string AreYouSureClearForm1Stats {
            get {
                return ResourceManager.GetString("AreYouSureClearForm1Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arrange as desired: 15, 14, 13, 12, 10, and 8..
        /// </summary>
        public static string ArrangeAsDesired {
            get {
                return ResourceManager.GetString("ArrangeAsDesired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] baseInfo {
            get {
                object obj = ResourceManager.GetObject("baseInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Challenging campaign.
        /// </summary>
        public static string ChallengingCampaign {
            get {
                return ResourceManager.GetString("ChallengingCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm cleaning?.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Election_2020_Background {
            get {
                object obj = ResourceManager.GetObject("Election-2020-Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Roll 4d6 six times, always discarding the lowest result. Once during this process, you can reroll the die that obtains the lowest result. Distribute the values as you wish..
        /// </summary>
        public static string EliteArrayText {
            get {
                return ResourceManager.GetString("EliteArrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a High-powered campaign.
        /// </summary>
        public static string HighPoweredCampaign {
            get {
                return ResourceManager.GetString("HighPoweredCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_close_window_24 {
            get {
                object obj = ResourceManager.GetObject("icons8-close-window-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icons8_google_24 {
            get {
                object obj = ResourceManager.GetObject("icons8-google-24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Character loaded successfully!.
        /// </summary>
        public static string LoadSavedCharacter {
            get {
                return ResourceManager.GetString("LoadSavedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logingoogle {
            get {
                object obj = ResourceManager.GetObject("logingoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Low-powered campaign.
        /// </summary>
        public static string LowPoweredCampaign {
            get {
                return ResourceManager.GetString("LowPoweredCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Character successfully saved!.
        /// </summary>
        public static string MsgSaveCharacter {
            get {
                return ResourceManager.GetString("MsgSaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap no_avatar {
            get {
                object obj = ResourceManager.GetObject("no_avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save Character.
        /// </summary>
        public static string OpenSaveCharacter {
            get {
                return ResourceManager.GetString("OpenSaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Load Character.
        /// </summary>
        public static string SelectFileToOpen {
            get {
                return ResourceManager.GetString("SelectFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Standard campaign.
        /// </summary>
        public static string StandardCampaign {
            get {
                return ResourceManager.GetString("StandardCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tong_hop_cac_mau_background_dep_nhat_10070 {
            get {
                object obj = ResourceManager.GetObject("tong-hop-cac-mau-background-dep-nhat-10070", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tougher campaign.
        /// </summary>
        public static string TougherCampaign {
            get {
                return ResourceManager.GetString("TougherCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to open link that was clicked.
        /// </summary>
        public static string UnableOpenLink {
            get {
                return ResourceManager.GetString("UnableOpenLink", resourceCulture);
            }
        }
    }
}
